// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:number,arg2:string,arg3:number):Promise<number>;

export function CreateStack(arg1:string):Promise<number>;

export function DeleteStack(arg1:number):Promise<number>;

export function DeleteTask(arg1:number):Promise<number>;

export function EditStack(arg1:number,arg2:string):Promise<number>;

export function EditTask(arg1:number,arg2:string):Promise<number>;

export function GetStacks():Promise<Array<main.Stack>>;

export function ReorderTasks(arg1:Array<main.Task>):Promise<Array<main.Task>>;

export function UpdateTaskDone(arg1:number,arg2:boolean):Promise<number>;
