// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function CreateStack(arg1) {
  return window['go']['main']['App']['CreateStack'](arg1);
}

export function DeleteStack(arg1) {
  return window['go']['main']['App']['DeleteStack'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function EditStack(arg1, arg2) {
  return window['go']['main']['App']['EditStack'](arg1, arg2);
}

export function EditTask(arg1, arg2) {
  return window['go']['main']['App']['EditTask'](arg1, arg2);
}

export function GetStack(arg1) {
  return window['go']['main']['App']['GetStack'](arg1);
}

export function GetStacks() {
  return window['go']['main']['App']['GetStacks']();
}

export function GetTags(arg1) {
  return window['go']['main']['App']['GetTags'](arg1);
}

export function ReorderTasks(arg1) {
  return window['go']['main']['App']['ReorderTasks'](arg1);
}

export function UpdateTaskDone(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskDone'](arg1, arg2);
}
